### ISSUE TITLE
ModuleNotFoundError: No module named 'preql.core'

### ISSUE THREAD

**Issue by Kreijstal** [erezsh/Preql#44]
trying to run `pipx run preql`
or in venv pip install preql and running preql throws this same error.
```
Traceback (most recent call last):
  File "C:\Users\j\scoop\apps\python\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\j\scoop\apps\python\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\j\ok\scripts\crawlformtool\Scripts\preql.exe\__main__.py", line 4, in <module>
  File "C:\Users\j\ok\scripts\crawlformtool\lib\site-packages\preql\__init__.py", line 1, in <module>
    from . import _base_imports
  File "C:\Users\j\ok\scripts\crawlformtool\lib\site-packages\preql\_base_imports.py", line 1, in <module>
    from .core import interp_common, pql_types, pql_objects, types_impl
ModuleNotFoundError: No module named 'preql.core'
```

**Comment by erezsh** [comment]
You're right, it was a bad build. Sorry for that!

I just released 0.2.7 which also includes various fixes. Give it a try.
